/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { mockServerPool } from "../mock-server/MockServerPool";
import { MyClientNameDevinClient } from "../../src/Client";

describe("Imdb", () => {
    test("createMovie", async () => {
        const server = mockServerPool.createServer();
        const client = new MyClientNameDevinClient({ environment: server.baseUrl });
        const rawRequestBody = { title: "title", rating: 1.1 };
        const rawResponseBody = "string";
        server
            .mockEndpoint()
            .post("/movies/create-movie")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.imdb.createMovie({
            title: "title",
            rating: 1.1,
        });
        expect(response).toEqual("string");
    });

    test("getMovie", async () => {
        const server = mockServerPool.createServer();
        const client = new MyClientNameDevinClient({ environment: server.baseUrl });

        const rawResponseBody = { id: "tt0111161", title: "The Shawshank Redemption", rating: 9.3 };
        server.mockEndpoint().get("/movies/tt0111161").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.imdb.getMovie("tt0111161");
        expect(response).toEqual({
            id: "tt0111161",
            title: "The Shawshank Redemption",
            rating: 9.3,
        });
    });
});
